apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-currency-exchange
spec:
  selector:
    matchLabels:
      app: crypto-currency-exchange
  template:
    metadata:
      labels:
        app: crypto-currency-exchange
    spec:
      containers:
      - name: crypto-currency-exchange
        image: ghorbaniali/solid-stack-app:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8000
