apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: GitOps/manifests/apps/crypto-app
    repoURL: https://github.com/ghorbani-ali/solid-stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
