---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-currency-exchange
spec:
  project: 
  source:
    repoURL: git@github.com:ghorbani-ali/solid-stack.git
    targetRevision: HEAD
    path: GitOps/manifests/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false