---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-currency-exchange
spec:
  project: default
  source:
    repoURL: https://github.com/ghorbani-ali/solid-stack.git
    targetRevision: HEAD
    path: GitOps/manifests/apps/crypto-currency-exchange
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false