apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.0.0
    helm:
      releaseName: grafana
      valueFiles:
      - $values/GitOps/manifests/infra/grafana/values-patch.yaml
  - repoURL: https://github.com/ghorbani-ali/solid-stack.git
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false