alloy:
  configMap:
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      loki.write "default" {
        endpoint {
          url = "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
        }
      }

      loki.source.kubernetes "logs" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.default.receiver]
      }
