Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-12"

  master = {
    "k8s-master1" => "192.168.56.101",
    "k8s-master2" => "192.168.56.102",
    "k8s-master3" => "192.168.56.103",
  }
  worker = {
    "k8s-worker1" => "192.168.56.104",
    "k8s-worker2" => "192.168.56.105"
  }

  master.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", 
        name: "k8s-subnet",
        ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.cpus = 2
        vb.memory = 2048
      end
    end
  end
  worker.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", 
        name: "k8s-subnet",
        ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.cpus = 4
        vb.memory = 4096
      end
    end
  end

end
