apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-app
  labels: 
    app: crypto-app
spec:
  selector:
    matchLabels:
      app: crypto-app
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
      - name: crypto-app
        image: ghorbaniali/solid-stack-app:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: crypto-app
        - secretRef:
            name: crypto-app
        ports:
        - name: http
          containerPort: 8000
